### ISSUE TITLE
Add a command to log somebody having their channel/bot access revoked

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#10]
Sometimes people get their permissions for channels taken away (for example, we have had to take away certain people's access to support/venting) and keeping track of that and who had their bot command access revoked in punishmentlog could be useful.

**Comment by catrenelle** [comment]
I'll add this to the current list of enhancements for the next push.

**Comment by minkses** [comment]
It'd probably make sense to just have it automatically log when !revoke is used and only use the new command for when somebody had their channel access restricted, come to think of it. I'm sure you thought of that yourself, though.

**Comment by catrenelle** [comment]
For a "new command" are you talking about when we modify a channel and set custom permissions per user? The bot doesn't look for channel changes and such. Right now, it only watches the ban list.

**Comment by minkses** [comment]
I figured we could just have a command akin to !warn and !heynow to simply log when we've made modifications to channel permissions to exclude a user, since we used to keep track of that in the spreadsheet too.

**Comment by catrenelle** [comment]
Gotcha! I better understand now. You want to create a case specifically for this type  of activity so that it logs with the rest of the data and is quickly searchable in the case database. Got it.

**Comment by catrenelle** [comment]
!revoke now creates an entry in the punishment logs system as an informational entry. Once lifted, it updates this entry to reflect that the user can now use bot commands again.

**Comment by catrenelle** [comment]
!timeout, !timeoutchannel, and !timeoutrole are all added. !timeout will backup user roles, kill them all, then add the timeout role. This can be lifted by using !timeout again on the user, which will then restore the old roles and update the punishment logs entry.
