### ISSUE TITLE
Retrofit existing warning/heynow list for users still around

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#11]
This will probably need a human touch as people are prone to changing their discord usernames and we don't have IDs on hand in the existing list. I'd gladly format the list in whatever way works best to facilitate this.

**Comment by catrenelle** [comment]
Attached is the format these need to be in with a few sample records from Transcord. If I can get the data in this format, I can import it. If not, then I am unable to import them.
[Template.xlsx](https://github.com/catrenelle/CatBot/files/1504019/Template.xlsx)

**Comment by catrenelle** [comment]
Imported
