### ISSUE TITLE
Add a discreet way for members to alert staff

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#13]
e.g.: !staffalert people are fighting over pineapples on pizza

The bot uses @ Staff in #bot-room with the message the user put in, which member used the command and where it was used, as well as deleting the message containing the original command.
Potentially make the bot pm whoever used the command to let them know staff has successfully been alerted.

**Comment by catrenelle** [comment]
!staffalert has been created.

Deletes the message, pm's the user about the message deletion and informs that staff has been notified, creates a regular message with the staff role mention in the bot info channel, and then posts the detailed embed in the bot info channel.

Still needs PM support for privacy, but I need to figure out how to make that work and keep the bot in a multi-guild setup. However, I consider this request done and will open a new request for the PM version later.
