### ISSUE TITLE
Make the bot respect "do not hug" role

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#14]
When !hug, !pat or !poke are used, the bot first checks if the user it is being used on has the "do not hug" role.
If the role is found, instead of performing the normal action, it replies "This user doesn't accept hugs, pats or pokes. Try a high five instead."
If the role is not found, proceed with hug/pat/poke as normal.

!high5 would probably be okay untouched, as it's less physical and/or intimate and/or invasive to most people.

**Comment by catrenelle** [comment]
This is now in production.
