### ISSUE TITLE
!role command no longer works

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#20]
Using _!role_ no longer gets any sort of reply from the bot and even using _!help role_ returns "Couldn't find command!"

**Comment by catrenelle** [comment]
This command was changed to !rolesummary. If I left it at !role, it would get confused with !roles. :)

**Comment by minkses** [comment]
Ah, makes sense. _!help_ still lists it as just _!role_, which is what was causing confusion for me.
