### ISSUE TITLE
Add an !alerthandled command

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#22]
The command lets the rest of staff know that the person who used it is taking care of a particular _!staffalert_ by editing the alert message to include "This alert is being handled by [staff member]" or something similar.
Additionally, alerts will need to be numbered as to enable using _!alerthandled [number]_ to denote which alert is being addressed.
Optionally, allow staff members to add a comment, if they'd like to specify what the issue was (in case the alert itself didn't specify) or how it was handled (_!alerthandled [number] [optional comment]_).

**Comment by catrenelle** [comment]
pulling this out of my dev queue
