### ISSUE TITLE
Clarify which user's registration results are which

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#23]
When the bot posts registration results in #entry, change the first line to mention whose results they are, e.g. "Registration Results for @[user]".
This helps us keep better track of who may need help with registering (and pick out who is likely a troll due to wanting to register with conflicting roles), especially when multiple people are registering at the same time.

**Comment by catrenelle** [comment]
Done in code, will be pushed later today to the server.

**Comment by catrenelle** [comment]
Done in code. Will be pushed later today.
