### ISSUE TITLE
Make trigger word notices more easily readable

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#31]
Add which trigger word was used in the notice, e.g. "[user] used the trigger word [word] in [channel]: [full message]" (potentially with the [word] being underlined?)
We'd like to keep the bot picking up on partial words as it makes it harder for people to circumvent and this addition makes it easier for us to see what exactly the bot picked up on and if it's of any concern to us.

**Comment by catrenelle** [comment]
This will be completed this evening when I get home. Won't take long to implement.

**Comment by catrenelle** [comment]
Done and in production
