### ISSUE TITLE
Allow the bot to not count messages in specified channels towards the message threshold

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#36]
A command that allows staff to specify channels in which the messages don't count towards the message threshold of the "New User" role. Prevents people from meeting the threshold by, for example, just adding/removing roles repeatedly by excluding channels such as random-voice-text, in Transcord's case.

**Comment by catrenelle** [comment]
Bot now only increments the counter for messages that are not bot  commands. Pushed to production.
