### ISSUE TITLE
Make the bot send a customizable PM to users once they are no longer considered a New User

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#37]
To let users know they're a full-fledged member now. Customizable so individual servers can specify which new privileges that offers (e.g. in Transcord's case, the message would mention access to additional channels and eligibility for nsfw roles).

**Comment by minkses** [comment]
Potentially add the feature for the bot to just post it in random-voice-text and @ the person if they've disabled receiving PMs?

**Comment by catrenelle** [comment]
I've added the bot private message, see !newusermessage (or !num). You can use the same replacement items that welcomemessage supports as well (IE: {user#}, {user}, etc.)

I don't feel we should post this to random-voice-text as this is something unique to the user and not something that should be posted publicly. If a user does not allow pm's, that's their fault. We should not have to work around this unless it were a critical message.

This is now active in Transcord.
