### ISSUE TITLE
Add the option to initially have the bot assign the New User role to new people, then replace it with the Member role

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#38]
Discord still prioritizes giving access over restricting it (regardless of the position of roles on the role list). Therefor, if one wants New Users not to have access to certain channels that Members do have access to, they cannot have both roles.
With this enabled (should maybe be able to be toggled, as I'd imagine not every server needs it set up like this), the bot first only assigns the New User role. Once all requirements are met, it removes said role and adds the Member role.

**Comment by catrenelle** [comment]
Bot now adds "New User" role upon registration if it exists. A register role must also exist.

Upon completion of New User role stipulations, it becomes removed and the register role is added (in Transcords case, the Member role). If there is no "New User" role, then the register role is instantly added, bypassing the New User system.

This is now launched on Transcord, but not pushed to GitHub yet.
