### ISSUE TITLE
Add an option to prevent the bot from assigning roles if not also assigning required roles

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#42]
Unfortunately, people don't read our instructions very well unless they're forced to do so.
Therefor, it'd be useful that, if a user uses _!register_ and this option is toggled, the bot cannot assign any roles unless at least one role of each required category is among the requested roles.

e.g.:
_!register mtf she/her_ assigns no roles, as no gender is being requested
_!register female mtf she/her_ assigns all requested roles, as a gender is among them

(Passing this one on from Lucas)

**Comment by catrenelle** [comment]
done
