### ISSUE TITLE
Add the option to add a customizable message from the staff to successful registrations

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#51]
To both the version posted in #entry & the one PMed to users.
Would allow us to remind newly registered users of the restrictions of the New User role, for example, as a lot of users seem to not notice this in the welcome message.

**Comment by minkses** [comment]
Can we bump this up to high priority? People keep getting confused about the New User role and implementing this could easily solve that.

**Comment by catrenelle** [comment]
Priority is just how I see it when stacked up against current tasks.

For a precise look at what is being worked on, see the Projects board at the top:
https://github.com/catrenelle/CatBot/projects/1

**Comment by catrenelle** [comment]
pulling this out of my dev queue
