### ISSUE TITLE
Add the option to force a role on people who do not register with a specific set of roles

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#52]
People keep circumventing registering as an ally by simply registering with "female/male, he/she" and leaving out ally.
This would essentially make the bot force (in Transcord's case) the ally role if it doesn't detect a user as registering with any role that clearly marks them as not cis (e.g. mtf, ftm, ftx, mtx, nonbinary, etc.).

(Suggested by Theta.)

**Comment by minkses** [comment]
Jumping off of this, it was also suggested to add the ability to force a country role on users if they only add a state/province/etc. to themselves.

e.g.:
A user uses _!addrole Texas_, the bot adds both Texas and USA to their roles.

Same goes for Canadian provinces and anything else that's comparable.

(Suggested by Theta.)

**Comment by catrenelle** [comment]
Removing this as I don't feel this needs to be in the bot.
