### ISSUE TITLE
Clarify failed user registrations

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#54]
Add to the "Required Roles" section of a failed registration which required category/categories of roles the user is missing, as well as generally making it more descriptive (e.g.: "Missing a required role from the [category] category. Cannot add the member role until this is corrected. Use _!rolelist_ to view your options, then _!register_ again. For roles not mentioned, ping @ Staff.").
Needs to accommodate missing roles of multiple required categories.

Additionally, the "Roles Not Found" section should not mention using _!addrole_ on failed registrations, as users will end up getting required roles without actually passing registration (also, in Transcord's case, _!addrole_ isn't set to work in the entry channel, so it just causes confusion).
It should still mention it on successful registrations, though, to let users know they can still add more roles.

**Comment by minkses** [comment]
Never mind the part of the issue concerning the "Roles Not Found" section. I realized immediately after posting that this will be fixed with the bot not adding roles at all unless required roles are also being added, as requested in issue #42.
My apologies.

**Comment by catrenelle** [comment]
done
