### ISSUE TITLE
Add an option to the !message command to make the bot preface it with an @ everyone

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#56]
It'd be nice to be able to tell the bot to use an _@ everyone_ without having to put that in the message itself, as it would alert all people with access to the bot channel.

e.g.: "_!message #the-lounge [true] [Shut up people]_" results in the bot saying "@ everyone Shut up people" in #the-lounge.

(Obviously _@ everyone_ would be without a space but github gets weird about me typing that :P)

**Comment by catrenelle** [comment]
This feature would take the same effort as prefacing the message with an everyone tag or a user tag. As a result, I’m closing this issue.

**Comment by minkses** [comment]
Wasn't really about effort, more so not giving all of staff extra notifications through the additional _@ everyone_ in the bot command.
