### ISSUE TITLE
Enhance !whowas

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#58]
Add a notice as to whether the person last left the server due to a kick.

**Comment by catrenelle** [comment]
This cannot be implemented at this time. Kicks are only logged when done with the kick command.

Current Discord.Net version cannot access audit logs and Discord does not specify that the user was kicked with the OnClientLeave event.

We will have to explore this option with the next Discord.Net release where the bot will actually have access to the Audit Log.
